{
 "cells": [
  {
   "metadata": {},
   "cell_type": "raw",
   "source": [
    "import sys, os\n",
    "sys.path.append(os.pardir)\n",
    "import pickle\n",
    "from dataset.mnist import load_mnist\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "#激活函数\n",
    "def sigmoid(x):\n",
    "    return 1 / (1 + np.exp(-x))\n",
    "\n",
    "def softmax(a):\n",
    "    c = np.max(a)\n",
    "    exp_a = np.exp(a - c)\n",
    "    sum_exp_a = np.sum(exp_a)\n",
    "    y = exp_a / sum_exp_a\n",
    "    return y\n",
    "\n",
    "def get_data():\n",
    "    (x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, flatten=True, one_hot_label=False)\n",
    "    return x_test, t_test\n",
    "\n",
    "def init_network():\n",
    "    with open(\"sample_weight.pkl\", 'rb') as f:\n",
    "        network = pickle.load(f)\n",
    "    return network\n",
    "def predict(network, x):\n",
    "    W1, W2, W3 = network['W1'], network['W2'], network['W3']\n",
    "    b1, b2, b3 = network['b1'], network['b2'], network['b3']\n",
    "    a1 = np.dot(x, W1) + b1\n",
    "    z1 = sigmoid(a1)\n",
    "    a2 = np.dot(z1, W2) + b2\n",
    "    z2 = sigmoid(a2)\n",
    "    a3 = np.dot(z2, W3) + b3\n",
    "    y = softmax(a3) #三层\n",
    "    return y\n",
    "\n",
    "# x,t = get_data()\n",
    "# network = init_network()\n",
    "# accuracy_count = 0\n",
    "# for i in range(len(x)):\n",
    "#     y = predict(network, x[i])\n",
    "#     p = np.argmax(y)\n",
    "#     print(p)\n",
    "#     if p == t[i]:\n",
    "#         accuracy_count += 1\n",
    "# print(\"Accuracy:\" + str(float(accuracy_count) / len(x)))\n",
    "\n",
    "#批处理\n",
    "x,t = get_data()\n",
    "network = init_network()\n",
    "batch_size = 100\n",
    "accuracy_count = 0\n",
    "for i in range(0, len(x), batch_size):\n",
    "    x_batch = x[i:i+batch_size]\n",
    "    y_batch = predict(network, x_batch)\n",
    "    p = np.argmax(y_batch, axis=1)\n",
    "    accuracy_count += np.sum(p == t[i:i+batch_size])\n",
    "print(\"Accuracy:\" + str(float(accuracy_count) / len(x)))"
   ],
   "id": "2ae5003055ae2e18"
  }
 ],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}
